### ISSUE TITLE
[Features] Build out component challenge generator CLI

### ISSUE THREAD

**Issue by smooto** [smooto/frontend-challenges#1]
because shell scripts are fun to write haha

### Generators
- "One-off" -- 1 random component, 1 random aesthetic
 - arg: 'hardmode' -- adds 1 random twist
- "Campaign" -- 1 random component, 5 random aesthetics; if hardmode, 5 random twists
 - arg: 'hardmode' -- adds 5 random twists
- others?

### To-do
- [ ] add help command and documentation for basic commands/args
- [ ] add hardmode arg handling
- [ ] add campaign option
- [ ] refactor/organize
- [ ] add interactivity?
- [ ] find more attributes to include

### UX/QoL notes
- Include an option to re-roll challenge after generating
- Include an option (at least for "Campaigns") to save the challenge as a text file?
- Include brief explanations/definitions of terms after generating? (i'm thinking off by default, flag or option to turn on)
- An interactive "wizard" would be fun to make and potentially useful for some users, but every option available in the wizard should also be available as a single-line input.
